#Docker compose si on veux uniquement run l'api avec une bdd
services:
  postgres:
    image: postgres:15
    container_name: goodfood_order_db_container
    ports:
      - '5437:5437'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: k?:u-Nu4&FM68Q!1Ez
      POSTGRES_DB: goodfood_order
      PGPORT: 5437