import { OrderItem } from 'src/domain/order-items/entities/order-items.entity';
import { Order } from 'src/domain/orders/entities/order.entity';
import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';

export class OrdersSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const orderRepo = dataSource.getRepository(Order);
    const orderItemRepo = dataSource.getRepository(OrderItem);

    const orders = [
      {
        id: 1,
        client_id: 1,
        restaurant_id: 1,
        status_id: 1,
        description: 'Livraison rapide souhaitée',
        subtotal: 24.00,
        delivery_costs: 4.5,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '12',
        street: 'Rue Faidherbe',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0633,
        lat: 50.6371,
        orderItems: [
          {
            id: 1,
            order_id: 1,
            menu_item_id: 1,
            quantity: 2,
            unit_price: 12.00,
            notes: 'Sans oignons',
            selected_option_value_ids: [1, 4],
          },
        ],
      },
      {
        id: 2,
        client_id: 3,
        restaurant_id: 3,
        status_id: 3,
        description: 'Ajouter des couverts',
        subtotal: 35.00,
        delivery_costs: 4.5,
        service_charge: 2.5,
        global_discount: 2.0,
        street_number: '8',
        street: 'Rue de la Clef',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0601,
        lat: 50.6357,
        orderItems: [
          {
            id: 2,
            order_id: 2,
            menu_item_id: 19,
            quantity: 2,
            unit_price: 17.50,
            notes: 'Bien cuit',
            selected_option_value_ids: [43, 46],
          },
        ],
      },
      {
        id: 3,
        client_id: 5,
        restaurant_id: 5,
        status_id: 4,
        description: 'Sans sonnette, appeler',
        subtotal: 44.00,
        delivery_costs: 5.0,
        service_charge: 3.0,
        global_discount: 0.0,
        street_number: '17',
        street: 'Rue Nationale',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0578,
        lat: 50.6365,
        orderItems: [
          {
            id: 3,
            order_id: 3,
            menu_item_id: 40,
            quantity: 2,
            unit_price: 22.00,
            notes: 'Sauce à part',
            selected_option_value_ids: [91, 94],
          },
        ],
      },
      {
        id: 4,
        client_id: 7,
        restaurant_id: 7,
        status_id: 5,
        description: 'Livraison au bureau',
        subtotal: 90.00,
        delivery_costs: 6.0,
        service_charge: 4.0,
        global_discount: 5.0,
        street_number: '5',
        street: 'Place Rihour',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0627,
        lat: 50.6351,
        orderItems: [
          {
            id: 4,
            order_id: 4,
            menu_item_id: 58,
            quantity: 2,
            unit_price: 45.00,
            notes: 'Sans gluten',
            selected_option_value_ids: [133, 136],
          },
        ],
      },
      {
        id: 5,
        client_id: 9,
        restaurant_id: 9,
        status_id: 2,
        description: 'Livraison express',
        subtotal: 70.00,
        delivery_costs: 5.5,
        service_charge: 3.5,
        global_discount: 0.0,
        street_number: '10',
        street: 'Rue de Gand',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0675,
        lat: 50.6413,
        orderItems: [
          {
            id: 5,
            order_id: 5,
            menu_item_id: 73,
            quantity: 2,
            unit_price: 35.00,
            notes: 'Sans crevettes',
            selected_option_value_ids: [169, 172],
          },
        ],
      },
      {
        id: 6,
        client_id: 4,
        restaurant_id: 2,
        status_id: 1,
        description: 'Emballage cadeau',
        subtotal: 40.00,
        delivery_costs: 4.0,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '22',
        street: 'Boulevard Vauban',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0489,
        lat: 50.6114,
        orderItems: [
          {
            id: 6,
            order_id: 6,
            menu_item_id: 13,
            quantity: 2,
            unit_price: 20.00,
            notes: 'Sauce BBQ',
            selected_option_value_ids: [31, 34],
          },
        ],
      },
      {
        id: 7,
        client_id: 6,
        restaurant_id: 6,
        status_id: 4,
        description: 'Livrer au 2e étage',
        subtotal: 35.00,
        delivery_costs: 4.5,
        service_charge: 2.5,
        global_discount: 0.0,
        street_number: '33',
        street: 'Rue du Molinel',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0654,
        lat: 50.6338,
        orderItems: [
          {
            id: 7,
            order_id: 7,
            menu_item_id: 49,
            quantity: 2,
            unit_price: 17.50,
            notes: 'Extra frites',
            selected_option_value_ids: [109, 112],
          },
        ],
      },
      {
        id: 8,
        client_id: 8,
        restaurant_id: 8,
        status_id: 3,
        description: 'Pas de sac plastique',
        subtotal: 33.00,
        delivery_costs: 4.5,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '28',
        street: 'Rue Esquermoise',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0589,
        lat: 50.6382,
        orderItems: [
          {
            id: 8,
            order_id: 8,
            menu_item_id: 67,
            quantity: 2,
            unit_price: 16.50,
            notes: 'Sans œuf',
            selected_option_value_ids: [151, 154],
          },
        ],
      },
      {
        id: 9,
        client_id: 10,
        restaurant_id: 10,
        status_id: 5,
        description: 'Livraison discrète',
        subtotal: 48.00,
        delivery_costs: 5.0,
        service_charge: 3.0,
        global_discount: 0.0,
        street_number: '19',
        street: 'Rue Solférino',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0612,
        lat: 50.6254,
        orderItems: [
          {
            id: 9,
            order_id: 9,
            menu_item_id: 85,
            quantity: 2,
            unit_price: 24.00,
            notes: 'Sauce à part',
            selected_option_value_ids: [193, 196],
          },
        ],
      },
      {
        id: 10,
        client_id: 1,
        restaurant_id: 4,
        status_id: 2,
        description: 'Ajouter serviettes',
        subtotal: 64.00,
        delivery_costs: 5.5,
        service_charge: 3.5,
        global_discount: 0.0,
        street_number: '12',
        street: 'Rue Faidherbe',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0633,
        lat: 50.6371,
        orderItems: [
          {
            id: 10,
            order_id: 10,
            menu_item_id: 31,
            quantity: 2,
            unit_price: 32.00,
            notes: 'Cuisson saignante',
            selected_option_value_ids: [73, 76],
          },
        ],
      },
      {
        id: 11,
        client_id: 3,
        restaurant_id: 1,
        status_id: 1,
        description: 'Livraison avant 20h',
        subtotal: 37.00,
        delivery_costs: 4.5,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '8',
        street: 'Rue de la Clef',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0601,
        lat: 50.6357,
        orderItems: [
          {
            id: 11,
            order_id: 11,
            menu_item_id: 4,
            quantity: 2,
            unit_price: 18.50,
            notes: 'Extra sauce',
            selected_option_value_ids: [7, 10],
          },
        ],
      },
      {
        id: 12,
        client_id: 5,
        restaurant_id: 6,
        status_id: 4,
        description: 'Sans emballage',
        subtotal: 28.00,
        delivery_costs: 4.0,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '17',
        street: 'Rue Nationale',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0578,
        lat: 50.6365,
        orderItems: [
          {
            id: 12,
            order_id: 12,
            menu_item_id: 50,
            quantity: 2,
            unit_price: 14.00,
            notes: 'Sans légumes',
            selected_option_value_ids: [115, 118],
          },
        ],
      },
      {
        id: 13,
        client_id: 7,
        restaurant_id: 9,
        status_id: 3,
        description: 'Livraison à l’entrée',
        subtotal: 48.00,
        delivery_costs: 5.0,
        service_charge: 3.0,
        global_discount: 0.0,
        street_number: '5',
        street: 'Place Rihour',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0627,
        lat: 50.6351,
        orderItems: [
          {
            id: 13,
            order_id: 13,
            menu_item_id: 76,
            quantity: 2,
            unit_price: 24.00,
            notes: 'Sans ail',
            selected_option_value_ids: [175, 178],
          },
        ],
      },
      {
        id: 14,
        client_id: 9,
        restaurant_id: 2,
        status_id: 5,
        description: 'Ajouter condiments',
        subtotal: 37.00,
        delivery_costs: 4.5,
        service_charge: 2.5,
        global_discount: 0.0,
        street_number: '10',
        street: 'Rue de Gand',
        city: 'Lille',
        postal_code: '59800',
        country: 'France',
        long: 3.0675,
        lat: 50.6413,
        orderItems: [
          {
            id: 14,
            order_id: 14,
            menu_item_id: 14,
            quantity: 2,
            unit_price: 18.50,
            notes: 'Extra lentilles',
            selected_option_value_ids: [37, 41],
          },
        ],
      },
      {
        id: 15,
        client_id: 10,
        restaurant_id: 8,
        status_id: 2,
        description: 'Livraison sans contact',
        subtotal: 22.00,
        delivery_costs: 4.0,
        service_charge: 2.0,
        global_discount: 0.0,
        street_number: '19',
        street: 'Rue Solférino',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        long: 3.0612,
        lat: 50.6254,
        orderItems: [
          {
            id: 15,
            order_id: 15,
            menu_item_id: 64,
            quantity: 2,
            unit_price: 11.00,
            notes: 'Sans cornichons',
            selected_option_value_ids: [145, 148],
          },
        ],
      },
    ];

    for (const typeData of orders) {
      const order = orderRepo.create({
        id: typeData.id,
        client_id: typeData.client_id,
        restaurant_id: typeData.restaurant_id,
        status_id: typeData.status_id,
        description: typeData.description,
        subtotal: typeData.subtotal,
        delivery_costs: typeData.delivery_costs,
        service_charge: typeData.service_charge,
        global_discount: typeData.global_discount,
        street_number: typeData.street_number,
        street: typeData.street,
        city: typeData.city,
        postal_code: typeData.postal_code,
        country: typeData.country,
        long: typeData.long,
        lat: typeData.lat,
      });

      await orderRepo.save(order);

      for (const itemData of typeData.orderItems) {
        const orderItem = orderItemRepo.create({
          id: itemData.id,
          order_id: order.id,
          menu_item_id: itemData.menu_item_id,
          quantity: itemData.quantity,
          unit_price: itemData.unit_price,
          notes: itemData.notes,
          selected_option_value_ids: itemData.selected_option_value_ids,
        });

        await orderItemRepo.save(orderItem);
      }
    }

    console.log('All orders inserted successfully!');
  }
}